# This file contains values from Cookiecutter

default_context:
  project_name: "simple_proxy"
  project_description: "A python project created by Martokk."
  organization: "v3services"
  license: "MIT"
  minimal_python_version: "3.10"
  github_name: "martokk"
  email: "25113632+martokk@users.noreply.github.com"
  version: "0.0.1"
  line_length: "100"
  create_container_docker_templates: "yes"
  create_cli_typer_templates: "yes"
  create_db_sqlmodel_templates: "no"
  create_server_fastapi_templates: "no"
  fastapi_sqlmodel_template_model_name: "user"
